export const transactions = [
  {
    category: "Зарплата",
    subcategory: null,
    type: "income",
    sum: 90000,
    account: "Наличные",
    id: 1,
  },
  {
    category: "Питание",
    subcategory: "Продукты",
    type: "expense",
    sum: 20000,
    account: "Наличные",
    id: 2,
  },
  {
    category: "Питание",
    subcategory: "Кафе / Рестораны",
    type: "expense",
    sum: 5000,
    account: "Наличные",
    id: 3,
  },
  {
    category: "Транспорт",
    subcategory: "Авто",
    type: "expense",
    sum: 3000,
    account: "Наличные",
    id: 4,
  },
  {
    category: "Транспорт",
    subcategory: "Такси",
    type: "expense",
    sum: 1000,
    account: "Наличные",
    id: 5,
  },
  {
    category: "Транспорт",
    subcategory: "Такси",
    type: "expense",
    sum: 1500,
    account: "Наличные",
    id: 6,
  },
  {
    category: "Инвестиции",
    subcategory: "Недвижимость",
    type: "income",
    sum: 70000,
    account: "Депозит",
    id: 7,
  },
];
